### ISSUE TITLE
便捷修改NPC倾向

### ISSUE THREAD

**Issue by SarineeSunny** [BlackTeaPie/CoT-Chinese-Mods#1]
开了作弊模式之后，给npc修改倾向仍然需要玩家手动填写倾向的英文名
可我哪知道都有什么英文名啊
所以码了个mod，给你把所有倾向全列出来了
[EasyCheatNPCInclinations.mod.zip](https://github.com/user-attachments/files/17072478/EasyCheatNPCInclinations.mod.zip)
![2](https://github.com/user-attachments/assets/4148583f-5e09-47c9-a376-08127f4568ac)

**Comment by BlackTeaPie** [comment]
已收录
