### ISSUE TITLE
身材管理小助手mod

### ISSUE THREAD

**Issue by SarineeSunny** [BlackTeaPie/CoT-Chinese-Mods#3]
名称：身材管理小助手
简介：在食物贮藏处增加了当前饮食、锻炼情况对体型影响情况的说明
作者：林夜无霜
备注：mod在附件里，mod对应游戏版本为0.5.3e，如果后续版本中作者对于身材变动的判定条件有变的话，本mod给出的结果可能会出现谬误
[GetPlumpnessChange.mod.zip](https://github.com/user-attachments/files/17113349/GetPlumpnessChange.mod.zip)

**Comment by BlackTeaPie** [comment]
已收录
